In [1]:
%pip install gensim

In [2]:
import pandas as pd
import numpy as np
from nltk.corpus import wordnet as wn

In [3]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [4]:
from gensim.models import Word2Vec

In [5]:
simlex = pd.read_csv("SimLex-999.txt", sep="\t")

In [6]:
simlex

word1        word2 POS  SimLex999  conc(w1)  conc(w2)  concQ  \
0       old          new   A       1.58      2.72      2.81      2   
1     smart  intelligent   A       9.20      1.75      2.46      1   
2      hard    difficult   A       8.77      3.76      2.21      2   
3     happy     cheerful   A       9.55      2.56      2.34      1   
4      hard         easy   A       0.95      3.76      2.07      2   
..      ...          ...  ..        ...       ...       ...    ...   
994    join      acquire   V       2.85      2.86      2.93      2   
995    send       attend   V       1.67      2.70      3.17      2   
996  gather       attend   V       4.80      2.75      3.17      2   
997  absorb     withdraw   V       2.97      3.11      3.04      2   
998  attend       arrive   V       6.08      3.17      3.22      2   

     Assoc(USF)  SimAssoc333  SD(SimLex)  
0          7.25            1        0.41  
1          7.11            1        0.67  
2          5.94            1        1.19  
3          5.85            1        2.18  
4          5.82            1        0.93  
..          ...          ...         ...  
994        0.00            0        0.99  
995        0.00            0        1.44  
996        0.00            0        1.97  
997        0.00            0        1.75  
998        0.00            0        1.18  

[999 rows x 10 columns]

In [7]:
simlex['POS'].unique()

array(['A', 'N', 'V'], dtype=object)

In [8]:
word_similarities = np.zeros(len(simlex))
missing = 0
c = 0
for i in zip(simlex['word1'], simlex['word2'], simlex['POS']):
  if len(wn.synsets(i[0])) == 0 or len(wn.synsets(i[1])) == 0:
    missing += 1
  w1 = wn.synset(i[0] + '.' + i[-1].lower() + '.01')
  w2 = wn.synset(i[1] + '.' + i[-1].lower() + '.01')
  word_similarities[c] = wn.path_similarity(w1, w2)
  c += 1

In [9]:
missing

0

In [10]:
word_similarities

array([0.33333333, 0.33333333, 1.        , 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 1.        , 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 1.        , 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333

In [11]:
wup_similarities = np.zeros(len(simlex))
c = 0
for i in zip(simlex['word1'], simlex['word2'], simlex['POS']):
  if len(wn.synsets(i[0])) == 0 or len(wn.synsets(i[1])) == 0:
    missing += 1
  w1 = wn.synset(i[0] + '.' + i[-1].lower() + '.01')
  w2 = wn.synset(i[1] + '.' + i[-1].lower() + '.01')
  wup_similarities[c] = wn.wup_similarity(w1, w2)
  c += 1

In [12]:
wup_similarities

array([0.5       , 0.5       , 1.        , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 1.        , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 1.        , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5    

In [13]:
import gensim.downloader as api
dataset = api.load("text8")
model = Word2Vec(dataset)

[==================================================] 100.0% 31.6/31.6MB downloaded


In [16]:
model.wv["hallway"]

KeyError: ignored

In [18]:
from scipy.spatial.distance import cosine
cos_similarities = np.zeros(len(simlex))
not_pairs = []
c = 0
for i in zip(simlex['word1'], simlex['word2']):
  if i[0] not in model.wv or i[1] not in model.wv:
    cos_similarities[c] = 0
    c += 1
    not_pairs.append(i)
  else:
    w1 = model.wv[i[0]]
    w2 = model.wv[i[1]]
    cos_similarities[c] = 1 - cosine(w1, w2)
    c += 1

In [19]:
not_pairs

[('hallway', 'corridor'),
 ('bubble', 'suds'),
 ('orthodontist', 'dentist'),
 ('doctor', 'orthodontist'),
 ('aisle', 'hallway'),
 ('classroom', 'hallway'),
 ('disorganize', 'organize')]

In [20]:
cos_similarities

array([ 3.45844805e-01,  2.63903707e-01,  6.19786084e-01,  5.48819840e-01,
        6.66725993e-01,  4.14391607e-01,  5.36174595e-01,  6.75246418e-01,
        6.66220963e-01,  5.85541070e-01,  5.04897118e-01,  2.80776888e-01,
        7.91408002e-01,  5.00259697e-01,  5.29236615e-01,  6.01289093e-01,
        4.41161156e-01,  3.45055491e-01,  8.24417114e-01,  4.83676046e-01,
       -3.69972400e-02,  6.01791084e-01,  3.81206542e-01,  6.48714840e-01,
        2.55651325e-01,  3.22314739e-01,  5.99021912e-01,  7.19181359e-01,
        5.61385751e-01, -1.52541874e-02,  7.31193185e-01,  7.85051584e-01,
        2.90605277e-01, -1.59327075e-01,  1.64898679e-01,  3.21496934e-01,
        6.38076305e-01,  1.83556199e-01,  2.54222631e-01,  5.58606446e-01,
        5.32486737e-01,  1.67801261e-01,  2.31014475e-01,  1.77769527e-01,
        5.28232515e-01,  1.35904133e-01,  2.39587232e-01,  7.18169391e-01,
        3.21050853e-01,  1.97003663e-01,  2.28888214e-01,  5.36596358e-01,
        3.96742344e-01,  

In [22]:
word_pairs = list(zip(simlex['word1'], simlex['word2']))

In [23]:
ranked_pairs_gold = [pair for _, pair in sorted(zip(simlex['SimLex999'], word_pairs))]
ranked_pairs_path = [pair for _, pair in sorted(zip(word_similarities, word_pairs))]
ranked_pairs_wup = [pair for _, pair in sorted(zip(wup_similarities, word_pairs))]
ranked_pairs_cos = [pair for _, pair in sorted(zip(cos_similarities, word_pairs))]

In [24]:
from scipy.stats import kendalltau

In [25]:
tau_path, p_value_path = kendalltau(ranked_pairs_gold, ranked_pairs_path)
tau_wup, p_value_wup = kendalltau(ranked_pairs_gold, ranked_pairs_wup)
tau_cos, p_value_cos = kendalltau(ranked_pairs_gold, ranked_pairs_cos)

In [26]:
tau_path

-0.002588938309513596

In [27]:
tau_wup

0.02067186962989722

In [28]:
tau_cos

0.020994483454125367

In [ ]:
ranked_pairs_gold.index(('way', 'manner'))

843

In [30]:
ranked_pairs_cos.index(('way', 'manner'))

710

In [ ]:
ranked_pairs_wup

[('couch', 'baseball'),
 ('gun', 'trick'),
 ('bath', 'trick'),
 ('dictionary', 'definition'),
 ('gun', 'dawn'),
 ('loop', 'belt'),
 ('mouse', 'management'),
 ('jail', 'choice'),
 ('word', 'dictionary'),
 ('choice', 'vein'),
 ('doctor', 'temper'),
 ('father', 'god'),
 ('fraternity', 'door'),
 ('belief', 'flower'),
 ('book', 'bible'),
 ('book', 'text'),
 ('flower', 'endurance'),
 ('money', 'diamond'),
 ('money', 'pearl'),
 ('pollution', 'president'),
 ('book', 'essay'),
 ('book', 'literature'),
 ('communication', 'television'),
 ('course', 'stomach'),
 ('heroine', 'hero'),
 ('people', 'balloon'),
 ('presence', 'door'),
 ('sinner', 'saint'),
 ('task', 'highway'),
 ('word', 'newspaper'),
 ('author', 'creator'),
 ('bone', 'teeth'),
 ('book', 'information'),
 ('book', 'story'),
 ('book', 'theme'),
 ('book', 'topic'),
 ('cent', 'wife'),
 ('creator', 'maker'),
 ('eye', 'tear'),
 ('god', 'prey'),
 ('newspaper', 'information'),
 ('advise', 'recommend'),
 ('beg', 'ask'),
 ('chapter', 'tail'),
 ('